server:
    port: 8080
    servlet:
      context-path: /ebook
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ebook?serverTimezone=Asia/Shanghai
    username: root
    password: shukai1415
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,slf4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    onnectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-wait: 500
        max-idle: 300
        max-active: 3000
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: ebook
  mail:
      host: smtp.qq.com
      username: 1491558763@qq.com
      password: zvobupxknebhjgfi
      properties.mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

